# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=2048)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Prod', 'Prod'), ('Staging', 'Staging')], default=None, max_length=20, null=True)),
            ],
        ),
    ]
